logging.level.org.springframework.cloud.gateway=DEBUG
# Puerto donde corre el Gateway
server.port=8081

# Ruta 1: Redirige todo lo que comience con /users/** al microservicio en el puerto 8081
spring.cloud.gateway.routes[0].id=productos
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/productos/**